name: 'Master CI Pipeline'
pr: none

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Backend
  steps:
  - task: Gradle@2
    name: 'Gradle_Build_And_Test'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'Cobertura'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      checkStyleRunAnalysis: true
  - task: CopyFiles@2
    name: 'Copy_binaries_to_staging_directory'
    inputs:
      Contents: '**/movie*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    name: 'Publish_artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- job: FrontEnd
  steps:
  - task: Npm@1
    name: 'npm_install'
    inputs:
      command: 'install'
      workingDir: 'movie-list-ui'
  - task: Npm@1
    name: 'npm_run_build'
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: 'movie-list-ui'
  - task: Npm@1
    name: 'npm_test'
    inputs:
      command: 'custom'
      customCommand: 'test'
      workingDir: 'movie-list-ui'
  - task: CopyFiles@2
    name: 'Copy_dist_files'
    inputs:
      Contents: 'movie-list-ui/dist/**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/ui'
  - task: PublishBuildArtifacts@1
    name: 'Publish_artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop-ui'
      publishLocation: 'Container'
