# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


# curl \
#  -X POST \
#  -H "Accept: application/vnd.github.v3+json" \
#  https://api.github.com/repos/octocat/hello-world/actions/workflows/42/dispatches \
#  -d '{"ref":"ref"}'

name: Java CI with Gradle

on:
  push:
    branches: [ $default-branch ] # main branch set on repository settings

  workflow_dispatch

jobs:
  build:
    name: "Build and publish artifacts"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: '**/movie*.jar'
  